#include "config.h"

#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <unistd.h>

namespace {

void require(bool condition, const char *message) {
  if (!condition) {
    std::cerr << message << std::endl;
    std::exit(1);
  }
}

std::string temporary_path() {
  char path[] = "/tmp/lupine-config-test.XXXXXX";
  int fd = mkstemp(path);
  require(fd >= 0, "mkstemp failed");
  close(fd);
  return path;
}

} // namespace

int main() {
  const std::string path = temporary_path();
  setenv("LUPINE_SERVER_FILE", path.c_str(), 1);

  setenv("LUPINE_SERVER", "environment:14833", 1);
  require(lupine_server_configuration() == "environment:14833",
          "environment override was not preferred");

  unsetenv("LUPINE_SERVER");
  {
    std::ofstream output(path);
    output << "# generated by rgpu attach\n\n  10.77.77.1:14833  \n";
  }
  require(lupine_server_configuration() == "10.77.77.1:14833",
          "endpoint file was not read and trimmed");

  {
    std::ofstream output(path);
    output << std::string(4097, 'x') << '\n';
  }
  require(lupine_server_configuration().empty(),
          "oversized endpoint configuration was accepted");

  unlink(path.c_str());
  std::cout << "config_test: PASS" << std::endl;
  return 0;
}
