#!/usr/bin/env python3
"""Generate the strict opaque-library fallback guard from a coverage audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SURFACE = ROOT / "rgpu-client/remote_gpu/unsupported_library_symbols.json"
DEFAULT_OUTPUT = ROOT / "rgpu-client/remote_gpu/unsupported_rpc_guard.c"
DEFAULT_COVERAGE = ROOT / "dev/results/raw/torch-gpu-symbol-coverage-round57.json"
STATUS = {"cublas": 13, "cusolver": 7, "nccl": 3}


def surface_from_coverage(path: Path) -> dict[str, object]:
    audit = json.loads(path.read_text(encoding="utf-8"))
    families = {
        family: sorted(audit["families"][family]["not_interposed_symbols"])
        for family in STATUS
    }
    return {
        "schema": 1,
        "source_artifact": path.name,
        "families": families,
        "total": sum(len(symbols) for symbols in families.values()),
    }


def render(surface: dict[str, object]) -> str:
    families = surface["families"]
    assert isinstance(families, dict)
    lines = [
        "/* Generated by dev/tools/generate_unsupported_guard.py. */",
        "#define _GNU_SOURCE",
        "#include <execinfo.h>",
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "#include <string.h>",
        "#include <unistd.h>",
        "",
        "static int rgpu_unsupported(const char *family, const char *symbol,",
        "                            int status, int *warned) {",
        "  if (!__atomic_exchange_n(warned, 1, __ATOMIC_RELAXED)) {",
        "    fprintf(stderr,",
        '            "rgpu: unsupported remote %s call: %s; no RPC route in "',
        '            "this release. Use --allow-unsupported-library-fallback "',
        '            "only to debug unsafe vendor fallback.\\n",',
        "            family, symbol);",
        '    const char *trace = getenv("RGPU_UNSUPPORTED_TRACE");',
        "    if (trace != NULL && trace[0] != '\\0' && strcmp(trace, \"0\") != 0) {",
        "      void *frames[32];",
        "      int count = backtrace(frames, 32);",
        "      backtrace_symbols_fd(frames, count, STDERR_FILENO);",
        "    }",
        "  }",
        '  const char *action = getenv("RGPU_UNSUPPORTED_ACTION");',
        '  if (action != NULL && strcmp(action, "abort") == 0) abort();',
        "  return status;",
        "}",
        "",
        "#define RGPU_UNSUPPORTED(FAMILY, SYMBOL, STATUS) \\",
        "  int SYMBOL(void) {                              \\",
        "    static int warned;                            \\",
        "    return rgpu_unsupported(FAMILY, #SYMBOL, STATUS, &warned); \\",
        "  }",
        "",
    ]
    for family in STATUS:
        symbols = families[family]
        assert isinstance(symbols, list)
        for symbol in symbols:
            lines.append(
                f'RGPU_UNSUPPORTED("{family}", {symbol}, {STATUS[family]})'
            )
    lines.extend(["", "#undef RGPU_UNSUPPORTED", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--coverage", type=Path)
    parser.add_argument("--surface", type=Path, default=DEFAULT_SURFACE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if args.coverage:
        surface = surface_from_coverage(args.coverage)
    elif args.surface.is_file():
        surface = json.loads(args.surface.read_text(encoding="utf-8"))
    else:
        surface = surface_from_coverage(DEFAULT_COVERAGE)

    expected_surface = json.dumps(surface, indent=2, sort_keys=True) + "\n"
    expected_output = render(surface)
    if args.check:
        if not args.surface.is_file() or args.surface.read_text() != expected_surface:
            raise SystemExit(f"stale unsupported-symbol surface: {args.surface}")
        if not args.output.is_file() or args.output.read_text() != expected_output:
            raise SystemExit(f"stale unsupported-symbol guard: {args.output}")
        return 0

    args.surface.parent.mkdir(parents=True, exist_ok=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.surface.write_text(expected_surface, encoding="utf-8")
    args.output.write_text(expected_output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
